# Generated by Django 5.2.8 on 2025-12-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NcsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.UUIDField(unique=True)),
                ('course_url', models.URLField()),
                ('course_name', models.CharField(blank=True, default='', max_length=500)),
                ('course_type', models.CharField(blank=True, default='', max_length=500)),
                ('learning_method', models.CharField(blank=True, default='', max_length=255)),
                ('course_hours', models.CharField(blank=True, default='', max_length=255)),
                ('course_stryd_time', models.CharField(blank=True, default='', max_length=255)),
                ('course_qualification_level', models.CharField(blank=True, default='', max_length=255)),
                ('course_description', models.TextField(blank=True, default='')),
                ('attendance_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('awarding_organization', models.CharField(blank=True, default='', max_length=500)),
                ('who_this_course_is_for', models.TextField(blank=True, default='')),
                ('entry_reeq', models.TextField(blank=True, default='')),
                ('college_name', models.CharField(blank=True, default='', max_length=500)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='')),
                ('duration', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.CharField(blank=True, default='', max_length=255)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
