# Generated by Django 5.2.8 on 2025-12-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncscourse',
            name='course_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ncscourse',
            name='website',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
