# Generated by Django 5.2.8 on 2025-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_ncscourse_course_url_alter_ncscourse_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncscourse',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncscourse',
            name='last_scrape_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ncscourse',
            name='last_scrape_run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ncscourse',
            name='last_scrape_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
