# Generated by Django 5.2.8 on 2025-12-22 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_ncscourse_last_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('postcode', models.CharField(blank=True, default='', max_length=64)),
                ('distance', models.IntegerField(default=0)),
                ('start_url', models.URLField(blank=True, default='', max_length=1000)),
                ('course_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='course_cour_created_5b85b5_idx'), models.Index(fields=['run_id', 'created_at'], name='course_cour_run_id_e4ebe7_idx'), models.Index(fields=['status', 'created_at'], name='course_cour_status_7b799a_idx')],
            },
        ),
    ]
