# Generated by Django 5.2.8 on 2025-12-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursescrapelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursescrapelog',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ncscourse',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='coursescrapelog',
            index=models.Index(fields=['category', 'created_at'], name='course_cour_categor_00f7e6_idx'),
        ),
    ]
