# Generated by Django 5.2.8 on 2025-12-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursescrapelog_category_ncscourse_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncscourse',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
