# Generated by Django 5.2.8 on 2025-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_ncscourse_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncscourse',
            name='cost_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
