# Generated by Django 5.2.8 on 2025-12-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_ncscourse_cost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncscourse',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
