# Generated by Django 5.2.8 on 2026-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_ncscourse_city_ncscourse_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncscourse',
            name='requirement_summery',
            field=models.TextField(blank=True, default=''),
        ),
    ]
