# Generated by Django 5.2.8 on 2025-12-23 13:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeshipVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_ref', models.CharField(db_index=True, max_length=32, unique=True)),
                ('vacancy_url', models.URLField(max_length=1000)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('employer_name', models.CharField(blank=True, default='', max_length=500)),
                ('location_summary', models.CharField(blank=True, default='', max_length=255)),
                ('closing_text', models.CharField(blank=True, default='', max_length=255)),
                ('posted_text', models.CharField(blank=True, default='', max_length=255)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('wage', models.CharField(blank=True, default='', max_length=255)),
                ('wage_extra', models.TextField(blank=True, default='')),
                ('training_course', models.CharField(blank=True, default='', max_length=500)),
                ('hours', models.CharField(blank=True, default='', max_length=500)),
                ('hours_per_week', models.CharField(blank=True, default='', max_length=64)),
                ('start_date', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.CharField(blank=True, default='', max_length=255)),
                ('positions_available', models.CharField(blank=True, default='', max_length=64)),
                ('work_intro', models.TextField(blank=True, default='')),
                ('what_youll_do_heading', models.CharField(blank=True, default='', max_length=255)),
                ('what_youll_do_items', models.TextField(blank=True, default='')),
                ('where_youll_work_name', models.CharField(blank=True, default='', max_length=500)),
                ('where_youll_work_address', models.TextField(blank=True, default='')),
                ('training_intro', models.TextField(blank=True, default='')),
                ('training_provider', models.CharField(blank=True, default='', max_length=500)),
                ('training_course_repeat', models.CharField(blank=True, default='', max_length=500)),
                ('what_youll_learn_items', models.TextField(blank=True, default='')),
                ('training_schedule', models.TextField(blank=True, default='')),
                ('more_training_information', models.TextField(blank=True, default='')),
                ('essential_qualifications', models.TextField(blank=True, default='')),
                ('skills_items', models.TextField(blank=True, default='')),
                ('other_requirements_items', models.TextField(blank=True, default='')),
                ('about_employer', models.TextField(blank=True, default='')),
                ('employer_website', models.URLField(blank=True, default='', max_length=1000)),
                ('company_benefits_items', models.TextField(blank=True, default='')),
                ('after_this_apprenticeship', models.TextField(blank=True, default='')),
                ('contact_name', models.CharField(blank=True, default='', max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_scrape_message', models.TextField(blank=True, default='')),
                ('last_scrape_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprenticeshipScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('start_url', models.URLField(blank=True, default='', max_length=1000)),
                ('vacancy_ref', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='apprentices_created_8de083_idx'), models.Index(fields=['run_id', 'created_at'], name='apprentices_run_id_7ae2cc_idx'), models.Index(fields=['status', 'created_at'], name='apprentices_status_4a7040_idx'), models.Index(fields=['category', 'created_at'], name='apprentices_categor_998a28_idx'), models.Index(fields=['vacancy_ref', 'created_at'], name='apprentices_vacancy_6380cb_idx')],
            },
        ),
    ]
