# Generated by Django 5.2.8 on 2025-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenticeship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenticeshipvacancy',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
