# Generated by Django 5.2.8 on 2026-01-09 14:
from django.db import migrations

class Migration(migrations.Migration):
    atomic = False  # REQUIRED for CREATE INDEX CONCURRENTLY

    dependencies = [
        ("apprenticeship", '0002_apprenticeshipvacancy_image_url'),  # <-- change to your latest apprenticeship migration
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Vacancy table
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_cat_subcat_idx "
                "ON apprenticeship_apprenticeshipvacancy (category, subcategory)",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_cat_subcat_scraped_at_idx "
                "ON apprenticeship_apprenticeshipvacancy (category, subcategory, scraped_at)",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_category_lower_idx "
                "ON apprenticeship_apprenticeshipvacancy (lower(category))",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_subcategory_lower_idx "
                "ON apprenticeship_apprenticeshipvacancy (lower(subcategory))",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_lower_cat_lower_sub_scraped_at_idx "
                "ON apprenticeship_apprenticeshipvacancy (lower(category), lower(subcategory), scraped_at)",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_vacancy_last_status_checked_at_idx "
                "ON apprenticeship_apprenticeshipvacancy (last_scrape_status, last_checked_at)",

                # Log table
                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_scrapelog_keyword_created_at_idx "
                "ON apprenticeship_apprenticeshipscrapelog (keyword, created_at)",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_scrapelog_cat_keyword_created_at_idx "
                "ON apprenticeship_apprenticeshipscrapelog (category, keyword, created_at)",

                "CREATE INDEX CONCURRENTLY IF NOT EXISTS apprenticeship_scrapelog_vacancy_ref_created_at_idx "
                "ON apprenticeship_apprenticeshipscrapelog (vacancy_ref, created_at)",
            ],
            reverse_sql=[
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_cat_subcat_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_cat_subcat_scraped_at_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_category_lower_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_subcategory_lower_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_lower_cat_lower_sub_scraped_at_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_vacancy_last_status_checked_at_idx",

                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_scrapelog_keyword_created_at_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_scrapelog_cat_keyword_created_at_idx",
                "DROP INDEX CONCURRENTLY IF EXISTS apprenticeship_scrapelog_vacancy_ref_created_at_idx",
            ],
        )
    ]
