# Generated by Django 5.2.8 on 2026-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenticeship', '0004_apprenticeshipvacancy_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenticeshipvacancy',
            name='requirement_summery',
            field=models.TextField(blank=True, default=''),
        ),
    ]
