# Generated by Django 5.2.8 on 2026-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenticeship', '0005_apprenticeshipvacancy_requirement_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenticeshipvacancy',
            name='ai_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apprenticeshipvacancy',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
