# Generated by Django 5.2.8 on 2025-12-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_type', models.CharField(choices=[('sector', 'Sector'), ('category', 'Category')], max_length=20)),
                ('sub_type', models.CharField(max_length=255)),
                ('job_slug', models.SlugField(max_length=255)),
                ('job_url', models.URLField()),
                ('jobname', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, default='')),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.CharField(blank=True, default='', max_length=255)),
                ('timings', models.CharField(blank=True, default='', max_length=255)),
                ('how_to_become', models.TextField(blank=True, default='')),
                ('college', models.TextField(blank=True, default='')),
                ('college_entry_req', models.TextField(blank=True, default='')),
                ('apprenticeship_entry_req', models.TextField(blank=True, default='')),
                ('apprenticeship', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('career_type', 'sub_type', 'job_slug')},
            },
        ),
    ]
