# Generated by Django 5.2.8 on 2025-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='last_scrape_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='last_scrape_run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='last_scrape_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
