# Generated by Django 5.2.8 on 2025-12-22 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0002_careerjob_last_checked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.CharField(blank=True, default='', max_length=20)),
                ('sub_type', models.CharField(blank=True, default='', max_length=255)),
                ('job_slug', models.CharField(blank=True, default='', max_length=255)),
                ('job_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='fetch_jobsc_created_55be2e_idx'), models.Index(fields=['run_id', 'created_at'], name='fetch_jobsc_run_id_70348b_idx'), models.Index(fields=['status', 'created_at'], name='fetch_jobsc_status_53a262_idx'), models.Index(fields=['route', 'sub_type', 'created_at'], name='fetch_jobsc_route_4a7384_idx')],
            },
        ),
    ]
