# Generated by Django 5.2.8 on 2025-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0003_jobscrapelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
