# Generated by Django 5.2.8 on 2026-01-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0006_alter_careerjob_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='careerjob',
            unique_together=set(),
        ),
    ]
