# Generated by Django 5.2.8 on 2026-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0007_alter_careerjob_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='dg_image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
