# Generated by Django 5.2.8 on 2026-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0009_careerembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='normalized_sub_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
