# Generated by Django 5.2.8 on 2026-09-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0010_careerjob_normalized_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='ai_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='work_location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='work_pace',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='work_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='careerjob',
            name='work_style',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
