# Generated by Django 5.2.8 on 2026-09-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch', '0011_careerjob_ai_fields_careerjob_ai_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjob',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
