# Generated by Django 5.2.8 on 2025-12-23 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DwpJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('job_url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('posting_date', models.CharField(blank=True, default='', max_length=255)),
                ('closing_date', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, default='', max_length=255)),
                ('job_reference', models.CharField(blank=True, default='', max_length=255)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('remote_working', models.CharField(blank=True, default='', max_length=255)),
                ('disability_confident', models.BooleanField(default=False)),
                ('listing_snippet', models.TextField(blank=True, default='')),
                ('apply_url', models.URLField(blank=True, default='', max_length=1000)),
                ('summary_intro', models.TextField(blank=True, default='')),
                ('summary_bullets', models.TextField(blank=True, default='')),
                ('what_youll_do_text', models.TextField(blank=True, default='')),
                ('what_youll_do_items', models.TextField(blank=True, default='')),
                ('skills_text', models.TextField(blank=True, default='')),
                ('skills_items', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_scrape_message', models.TextField(blank=True, default='')),
                ('last_scrape_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('start_url', models.URLField(blank=True, default='', max_length=1000)),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='job_jobscra_created_b94c23_idx'), models.Index(fields=['run_id', 'created_at'], name='job_jobscra_run_id_3f6c4e_idx'), models.Index(fields=['status', 'created_at'], name='job_jobscra_status_9bc8e0_idx'), models.Index(fields=['category', 'created_at'], name='job_jobscra_categor_3c174b_idx'), models.Index(fields=['job_id', 'created_at'], name='job_jobscra_job_id_480d61_idx')],
            },
        ),
    ]
