# Generated by Django 5.2.8 on 2025-12-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobscrapelog',
            name='job_jobscra_job_id_480d61_idx',
        ),
        migrations.RenameField(
            model_name='dwpjob',
            old_name='skills_items',
            new_name='additional_salary_information',
        ),
        migrations.RenameField(
            model_name='dwpjob',
            old_name='skills_text',
            new_name='skills_youll_need',
        ),
        migrations.RenameField(
            model_name='dwpjob',
            old_name='what_youll_do_items',
            new_name='what_youll_do',
        ),
        migrations.RenameField(
            model_name='jobscrapelog',
            old_name='keyword',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='dwpjob',
            name='what_youll_do_text',
        ),
        migrations.AlterField(
            model_name='dwpjob',
            name='job_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='jobscrapelog',
            index=models.Index(fields=['subcategory', 'created_at'], name='job_jobscra_subcate_20adc8_idx'),
        ),
    ]
