# Generated by Django 5.2.8 on 2025-12-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobscrapelog_job_jobscra_job_id_480d61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobscrapelog',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
