# Generated by Django 5.2.8 on 2025-12-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobscrapelog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobscrapelog',
            name='image_url',
        ),
        migrations.AddField(
            model_name='dwpjob',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
