# Generated by Django 5.2.8 on 2025-12-29 08:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_enable_pg_trgm'),
    ]
    operations = [
        migrations.AddIndex(
            model_name='dwpjob',
            index=django.contrib.postgres.indexes.GinIndex(fields=['location'], name='job_location_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
