# Generated by Django 5.2.8 on 2026-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_best_job_indexes_concurrently'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpjob',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dwpjob',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dwpjob',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='dwpjob',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dwpjob',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
