# Generated by Django 5.2.8 on 2026-01-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_dwpjob_city_dwpjob_latitude_dwpjob_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwpjob',
            name='requirement_summery',
            field=models.TextField(blank=True, default=''),
        ),
    ]
